### ISSUE TITLE
数据集处理

### ISSUE THREAD

**Issue by xidianwang412** [Hanjingzhou/Web2vec#3]
你好，请问原始数据是怎么处理后得到data2数据的，这块有相关的代码或者处理方式说明文档吗

**Comment by Hanjingzhou** [comment]
这是已经毕业的一个师兄写的，我只是代为上传到github上，所以没有处理原始数据相关的代码，但是有论文，你可以看论文里的处理办法，论文名是这Web2Vec Phishing Webpage Detection Method Based on Multidimensional Features Driven by Deep Learning。而且我的研究方向并不是钓鱼网站，所以只能给你这点帮助了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年6月22日(周二) 下午4:18
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Hanjingzhou/Web2vec] 数据集处理 (#3)




 
你好，请问原始数据是怎么处理后得到data2数据的，这块有相关的代码或者处理方式说明文档吗

**Comment by xidianwang412** [comment]
好的，多谢

> 这是已经毕业的一个师兄写的，我只是代为上传到github上，所以没有处理原始数据相关的代码，但是有论文，你可以看论文里的处理办法，论文名是这Web2Vec Phishing Webpage Detection Method Based on Multidimensional Features Driven by Deep Learning。而且我的研究方向并不是钓鱼网站，所以只能给你这点帮助了
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2021年6月22日(周二) 下午4:18 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [Hanjingzhou/Web2vec] 数据集处理 (#3) 你好，请问原始数据是怎么处理后得到data2数据的，这块有相关的代码或者处理方式说明文档吗 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

好的，多谢哈
